In [5]:
import numpy as np

In [6]:
mylist = [1,2,3,4,5]

In [7]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [8]:
nested_list = [[1,2,3],[4,5,6]]

In [9]:
np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.arange(0,11, 3)

array([0, 3, 6, 9])

In [11]:
np.zeros(2)

array([0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.zeros((6,6)) # (rows, columns)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((9,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.linspace(1,8,3)

array([1. , 4.5, 8. ])

In [16]:
np.eye(5) #Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.56521645, 0.32615517, 0.24949918, 0.02977321, 0.25734274])

In [18]:
np.random.rand(2,5)

array([[0.54886926, 0.51173524, 0.64317524, 0.59403632, 0.70281172],
       [0.49864862, 0.24627894, 0.21696229, 0.8214694 , 0.49273145]])

In [19]:
np.random.randint(2,11, (3,5))

array([[8, 8, 8, 4, 8],
       [5, 2, 2, 6, 8],
       [3, 6, 9, 8, 9]])

In [20]:
np.random.randn(2,9) #mean is 0 and standard deviation is 1

array([[-0.58275269,  0.78363076, -0.59972811, -1.14391784,  0.82941535,
        -0.53587686,  0.45771635, -0.1459767 , -1.36157722],
       [-0.87190934,  1.43294897, -1.27174369,  0.47950213,  0.22290431,
        -0.6211913 ,  0.78405957, -0.72591557, -0.90352888]])

In [21]:
np.random.seed(42) # Set the random seed for reproducibility
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
 arr.shape

(25,)

In [25]:
arr = arr.reshape(5,5)

In [26]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr.max()

24

In [28]:
arr.min()

0

In [29]:
arr.argmax()

24

In [30]:
arr.argmin()

0

In [31]:
arr.dtype

dtype('int64')

In [32]:
randarr = np.random.rand(1,99,21)

In [33]:
randarr

array([[[0.15601864, 0.15599452, 0.05808361, ..., 0.29214465,
         0.36636184, 0.45606998],
        [0.78517596, 0.19967378, 0.51423444, ..., 0.9093204 ,
         0.25877998, 0.66252228],
        [0.31171108, 0.52006802, 0.54671028, ..., 0.28093451,
         0.54269608, 0.14092422],
        ...,
        [0.96339443, 0.56016818, 0.93682246, ..., 0.22531693,
         0.25096666, 0.85061606],
        [0.56122279, 0.52339091, 0.11476887, ..., 0.54543187,
         0.06227311, 0.51250265],
        [0.80640362, 0.45923988, 0.05195658, ..., 0.02716742,
         0.06520459, 0.46393138]]])

In [34]:
randarr.dtype

dtype('float64')

In [35]:
len(randarr)

1

In [36]:
randarr.size

2079

In [37]:
arr = np.arange(25,50)

In [38]:
arr

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [39]:
arr[0]

25

In [40]:
arr[-1]

49

In [41]:
arr.max()

49

In [42]:
arr[9:11]

array([34, 35])

In [43]:
arr[:9]

array([25, 26, 27, 28, 29, 30, 31, 32, 33])

In [44]:
arr[14:]

array([39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
arr[arr.size-1]

49

In [48]:
arr[:9] = 100

In [49]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [57]:
slice_of_arr = arr[:9]

In [58]:
slice_of_arr[:] = 101

In [59]:
slice_of_arr

array([101, 101, 101, 101, 101, 101, 101, 101, 101])

In [60]:
arr

array([101, 101, 101, 101, 101, 101, 101, 101, 101,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [61]:
arr_copy = arr.copy()

In [62]:
arr_copy

array([101, 101, 101, 101, 101, 101, 101, 101, 101,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [63]:
arr_copy[:] = 0

In [64]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [65]:
arr

array([101, 101, 101, 101, 101, 101, 101, 101, 101,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [68]:
nested_arr = np.array([[9,10,11], [12,13,14],[99,101,102]])

In [69]:
nested_arr

array([[  9,  10,  11],
       [ 12,  13,  14],
       [ 99, 101, 102]])

In [71]:
nested_arr[2]

array([ 99, 101, 102])

In [72]:
nested_arr[:2]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [74]:
nested_arr[2][1]

101

In [75]:
nested_arr[:2,:1]

array([[ 9],
       [12]])

In [77]:
nested_arr[1:,1:]

array([[ 13,  14],
       [101, 102]])

In [78]:
arr = np.arange(20,99, 3)

In [79]:
arr

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68,
       71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [80]:
arr>50

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [81]:
bool_arr = arr>50

In [82]:
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [83]:
arr[bool_arr]

array([53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [84]:
arr[arr<50]

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [85]:
arr = np.arange(20,31)

In [86]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [87]:
arr - 5

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [88]:
arr + 5

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [89]:
arr * 5

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150])

In [90]:
arr + arr

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [91]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
arr * arr

array([400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900])

In [93]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [94]:
arr / 0

<ipython-input-94-db39a1c38901>:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [95]:
arr[0] = 0

In [96]:
arr / 0

<ipython-input-96-db39a1c38901>:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
<ipython-input-96-db39a1c38901>:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [97]:
arr[1]/arr[0]

<ipython-input-97-91c86cfa4267>:1: RuntimeWarning: divide by zero encountered in scalar divide
  arr[1]/arr[0]


inf

In [98]:
arr[0]/arr[1]

0.0

In [99]:
arr.sum()

255

In [100]:
arr.mean()

23.181818181818183

In [101]:
arr.var()

61.239669421487605

In [102]:
arr.std()

7.825577896966307

In [104]:
np.sqrt(arr)

array([0.        , 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558])

In [105]:
np.sin(arr)

array([ 0.        ,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162])

In [106]:
np.cos(arr)

array([ 1.        , -0.54772926, -0.99996083, -0.53283302,  0.42417901,
        0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753,
        0.15425145])

In [107]:
np.log(arr)

<ipython-input-107-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738])

In [109]:
arr[0] = -99
np.absolute(arr)

array([99, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [110]:
arr2d = np.arange(20).reshape(4,5)

In [111]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [112]:
arr2d.sum()

190

In [113]:
arr2d.sum(axis = 0)

array([30, 34, 38, 42, 46])

In [114]:
arr2d.sum(axis = 1)

array([10, 35, 60, 85])

##Exercise

In [115]:
import numpy as np

In [117]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [118]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [122]:
arr = np.arange(0,10)
arr[:] = 5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [123]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [125]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [126]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [132]:
np.random.rand(1)

array([0.90922021])

In [133]:
np.random.randn(25)

array([-0.18047991,  3.19310757,  0.29875291, -0.75179105, -0.4263576 ,
        1.14844571,  0.11327041, -1.43827798,  0.91922893, -0.66814409,
        1.87329778,  1.08004807, -0.4473219 ,  1.28101636,  0.06785551,
        0.85277368,  0.48473282, -0.84635665, -0.64354983,  1.02996082,
       -0.33477533, -0.40364846, -0.95512258,  0.42359907,  2.06252492])

In [140]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [141]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [143]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [144]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [146]:
mat[3][-1]

20

In [147]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [148]:
mat[4]

array([21, 22, 23, 24, 25])

In [150]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [152]:
mat.sum()

325

In [153]:
mat.std()

7.211102550927978

In [154]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [159]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])